### ISSUE TITLE
TODO help & docs

### ISSUE THREAD

**Issue by mawosoft** [mawosoft/WindowsSearchManager#5]
- [x] Actual content, obviously.
  Cmdlet help; API XmlDoc for POCOs.

- [x] #7
  WindowsSearchManager->(cmdlets), MPW->MWP->(api)
  If linking to api index page, we get two separate tocs.
  Also \<WBR\>s are not applied to MPW.

- [x] *powershell* hljs doesn't work well for syntax blocks (see build/convertPlatyPStoDocFxMarkdown.ps1)
  Should probably different lang and customized for proper highlighting.

- [x] platyPS generates wrong Syntax. Brackets and required doesn't always match.
  Either fix manually (gets overwritten when using Update-MarkdownHelpModule) or programatically in build/convertPlatyPStoDocFxMarkdown.ps1.

- [x] More problems with platyPS. The parameter order in the MAML file doesn't match the markdown source (even if unedited and coming from platyPS itself). Seems to be alphabetical.
  ~~Oddly enough, if one specifies `-AlphabeticParamsOrder` for New-MarkdownHelp, the order in the syntax block is preserved.~~ That was a fluke that occurs randomly.

- [x] New problems with stand-alone gh-pages.yml.
  Failed on ubuntu-latest and sdk 7.0.200, fine on win and sdk 7.0.103.
  Also `--no-restore` should be added to `dotnet build`
  Definitely a problem with sdk 7.0.200 (the msbuild version is labeled 17.5-preview) and docfx 2.62.1 - whoever the culprit is between them.
~Pinning the sdk to 7.0.103 in global.json doesn't help if 7.0.200 is also installed.
Also, dotnet info suddenly says it did not find a global.json.~
This was due to rollForward:disable`d` instead of `disable`. Talk about misleading messages...
So, pinning **DOES** work and we need to run on Win anyway because we need the Win SDK.
